購入履歴の表示に必要な関数の作成および表示ページの作成を実施 #10
tunacats/lamp_practice pull request #13
Opened 2021-10-19 16:23 UTC by tunacats

以下、ご確認をお願いいたします。
※購入明細の実装がまだのため、一部phpmyadminで購入明細で実装予定のSQLを書いて動作確認をしております。
管理者に関する要件は一旦後で追加しようかと思います。

■const.php
購入履歴（HISTORY_URL)を追記

■order_history.php
購入履歴のための処理を新規作成

■cart.php
order_historiesテーブルに挿入を行うための関数を作成（insert_history)
購入時の処理を行う関数(purchase_cart)へ購入履歴へデータを挿入するための処理を追記

■order_history_view.php
購入履歴を表示するためのページを新規作成

■header_logined.php 
ヘッダー部分に購入履歴を表示するように編集

2021-10-19 16:37 UTC, primestyleus requested changes
@tunacats 

大きな問題ないはなさそうですが、トランザクションがこれだとうまく動きません。ただ、detailsテーブルへの保存もまだ未完成のようなので、そこも対応した上で、再度トランザクションについては検討してみてください。

- 課題2・追加テーブルへのデータ保存
- 課題3・追加画面の作成

いずれかが完了していたら一旦マージすることもできるのですが、今現在の状態だといずれも未完成のようですので、一旦マージもPendingとさせていただきます。

2021-10-20 02:22 UTC, tunacats commented
detailsテーブルへの保存も行うため、購入明細まで作成しました。ご確認をお願いいたします。

2021-10-21 17:47 UTC, tunacats commented
■トランザクション処理について
　お話いただいておりましたエラーメッセージの有無をif文で判断し、commit/rollback処理を分岐させています。
　より良い方法がありましたら、ご教示いただけますと幸いです。

■購入明細の表示について
　購入履歴より選択された注文に対する明細のみ表示するように変更いたしました。
　※若干無理があるコーディングな気がしますので、より良い方法がありましたらご教示ください。

■管理者の購入履歴について
 一旦実装いたしました。管理者側で確認できる項目としてユーザ名もあったほうが良いような気もしますが
　ひとまず注文番号が一意なので照合はできるかと思い、こちらで実装しています。

ご確認の程よろしくお願いいたします。

2021-10-21 22:40 UTC, primestyleus requested changes
@tunacats 
get_errorsの部分だけは不具合につながるので修正をお願いします。それ以外はできればで大丈夫です。

2021-10-21 22:40 UTC, primestyleus commented on www/model/cart.php
> +  $error = get_errors();
考えとしてはよいです。トランザクションの制御も問題ないのですが、get_errorsを使ってしまうと、セッションに保存されたエラーがリセットされてしまうので、その後の画面でエラーが表示されない、という別の問題が起きてしまいます。

2021-10-21 22:40 UTC, primestyleus commented on www/html/order_detail.php
> +    $selected_history = $histories[$array_number];
ここは要件としては問題ないですが、いったん全件とったあとに1件を取り出す処理をしているため、無駄が生じています。できればDBから取り出す時点で1件だけとなるほうがいいです。

2021-10-21 22:40 UTC, primestyleus commented on www/view/order_history_view.php
> +                            <td><?= h($history['total']); ?></td>
ここ以外もですが、数字の表示にはnumber_formatを使いましょう。

2021-10-22 02:44 UTC, tunacats commented on www/model/cart.php
> +  $error = get_errors();
既存関数でhas_errorが使えそうかと思い、一旦使用しております。ご確認ください。

2021-10-22 02:45 UTC, tunacats commented on www/html/order_detail.php
> +    $selected_history = $histories[$array_number];
Slackでの回答ありがとうございました。
GROUP BYをつけることにより解決いたしました。
また、管理者については呼び出す関数を分岐してみましたので、ご確認ください。

2021-10-22 02:46 UTC, tunacats commented on www/view/order_history_view.php
> +                            <td><?= h($history['total']); ?></td>
createdのような日付の場合は、htmlspecialcharsで問題なかったでしょうか。
ひとまず、totalやorder_id, item_idなど数値以外の値が入らない場所に関しては、全てnumber_formatへ変更いたしました。

2021-10-22 02:52 UTC, primestyleus approved these changes
@tunacats 
一点コメントしました。お手すきでまた修正いただければと思います。大きな問題ではないので、いったんこちらでマージします。

2021-10-22 02:52 UTC, primestyleus commented on www/view/admin_view.php
> +                  <input  type="text" name="stock" value="<?= number_format($item['stock']); ?>">
すみません、説明が足りていませんでした。直接表示している部分にはnumber_formatを使っていただきたいのですが、valueに設定すると、本来inputの中は数値だけであるべきところに、カンマが入ってしまうので、あまりよくないです。

2021-10-22 02:52 UTC, merged